[package]
name = "integraal"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
rand = { version = "0.9.0-alpha.1", features = ["small_rng"] }

[[example]]
name = "rectangle_hardcoded"
path = "examples/rectangle/hardcoded.rs"

[[example]]
name = "rectangle_integraal"
path = "examples/rectangle/integraal.rs"

[[example]]
name = "trapezoid_hardcoded"
path = "examples/trapezoid/hardcoded.rs"

[[example]]
name = "trapezoid_integraal"
path = "examples/trapezoid/integraal.rs"

[[example]]
name = "montecarlo_hardcoded"
path = "examples/montecarlo/hardcoded.rs"

[[example]]
name = "montecarlo_integraal"
path = "examples/montecarlo/integraal.rs"